// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roll20Stats.InfrastructureLayer.DAL.Context;

namespace Roll20Stats.InfrastructureLayer.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201203131922_Extend_Playerstatistics_And_Game")]
    partial class Extend_Playerstatistics_And_Game
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Roll20Stats.InfrastructureLayer.DAL.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Roll20Stats.InfrastructureLayer.DAL.Entities.PlayerStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CharacterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharacterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PlayerStatistics");
                });

            modelBuilder.Entity("Roll20Stats.InfrastructureLayer.DAL.Entities.PlayerStatistic", b =>
                {
                    b.HasOne("Roll20Stats.InfrastructureLayer.DAL.Entities.Game", "Game")
                        .WithMany("PlayerStatistics")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Roll20Stats.InfrastructureLayer.DAL.Entities.Game", b =>
                {
                    b.Navigation("PlayerStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
